<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\YourAppName.Data\YourAppName.Data.csproj" />
    <ProjectReference Include="..\YourAppName.Infrastructure\YourAppName.Infrastructure.csproj" />
    <ProjectReference Include="..\YourAppName.Shared\YourAppName.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Twilio" Version="7.14.9" />
  </ItemGroup>

</Project>
