<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.1.1" />
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageReference Include="MediatR" Version="14.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\YourAppName.Data\YourAppName.Data.csproj" />
    <ProjectReference Include="..\YourAppName.Service\YourAppName.Service.csproj" />
    <ProjectReference Include="..\YourAppName.Shared\YourAppName.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Features\Auth\Queries\" />
    <Folder Include="Mapping\Roles\CommandMapping\" />
    <Folder Include="Mapping\Roles\QueryMapping\" />
  </ItemGroup>

</Project>
